# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink:        pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Matt Bond Portfolio
tagline:          'The portfolio of Matt Bond'
description:      'A San Francisco based Product Designer.'
url:              http://matbond.com.au
baseurl:          /
